[package]
name = "war_wolf_db_error"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
miette = { version = "7.2.0", features = ["fancy"] }
thiserror = "1"
